### ISSUE TITLE
Custom Formatting

### ISSUE THREAD

**Issue by archiewood** [sdebruyn/inzight#3]
This is such a cool use of open data to create something insightful!

I notice whenever you are referring to Energy values you are appending kWh.

You may be interested in defining a [custom format](https://docs.evidence.dev/features/value-formatting) in the settings menu (using excel-style format codes), which would remove the need for you to do this in each place!

**Comment by sdebruyn** [comment]
@archiewood Thank you for the review!!! Really appreciated 🙌

**Comment by sdebruyn** [comment]
Blocked by https://github.com/evidence-dev/evidence/issues/638

**Comment by sdebruyn** [comment]
implemented :)
